"""initial schema: tickers, snapshots, contracts

Revision ID: da5c89f6a74a
Revises:
Create Date: 2026-09-12 20:37:18.906707

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da5c89f6a74a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=256), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tickers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tickers_symbol"), ["symbol"], unique=True)

    op.create_table(
        "snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("spot", sa.Float(), nullable=False),
        sa.Column("risk_free_rate", sa.Float(), nullable=False),
        sa.Column("dividend_yield", sa.Float(), nullable=False),
        sa.Column("contract_count", sa.Integer(), nullable=False),
        sa.Column("solved_count", sa.Integer(), nullable=False),
        sa.Column("atm_iv_30d", sa.Float(), nullable=True),
        sa.Column("atm_iv_front", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ticker_id"], ["tickers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker_id", "snapshot_date", name="uq_snapshot_ticker_date"),
    )
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_snapshot_ticker_date", ["ticker_id", "snapshot_date"], unique=False
        )

    op.create_table(
        "contracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("right", sa.String(length=4), nullable=False),
        sa.Column("contract_symbol", sa.String(length=64), nullable=True),
        sa.Column("bid", sa.Float(), nullable=True),
        sa.Column("ask", sa.Float(), nullable=True),
        sa.Column("last", sa.Float(), nullable=True),
        sa.Column("mid", sa.Float(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("open_interest", sa.Integer(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("price_source", sa.String(length=8), nullable=True),
        sa.Column("time_to_expiry", sa.Float(), nullable=False),
        sa.Column("moneyness", sa.Float(), nullable=False),
        sa.Column("iv", sa.Float(), nullable=True),
        sa.Column("iv_status", sa.String(length=24), nullable=False),
        sa.Column("delta", sa.Float(), nullable=True),
        sa.Column("gamma", sa.Float(), nullable=True),
        sa.Column("vega", sa.Float(), nullable=True),
        sa.Column("theta", sa.Float(), nullable=True),
        sa.Column("rho", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["snapshot_id"], ["snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id", "expiry", "strike", "right", name="uq_contract_snapshot_key"
        ),
    )
    with op.batch_alter_table("contracts", schema=None) as batch_op:
        batch_op.create_index("ix_contract_expiry", ["snapshot_id", "expiry"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contracts", schema=None) as batch_op:
        batch_op.drop_index("ix_contract_expiry")

    op.drop_table("contracts")
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_snapshot_ticker_date")

    op.drop_table("snapshots")
    with op.batch_alter_table("tickers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tickers_symbol"))

    op.drop_table("tickers")
    # ### end Alembic commands ###
