/**
 * The cross-language contract test.
 *
 * `api/tests/fixtures/payoff_golden.json` is generated by the Python engine and
 * read by both suites. If this TypeScript preview and the Python implementation
 * ever disagree, this file goes red — which is the only reason it is safe to
 * have the same maths written twice.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  analysePayoff,
  buildPayoffCurve,
  describePosition,
  LegError,
  legCost,
  OPTION_MULTIPLIER,
  payoffAtExpiry,
  type Leg,
} from "./payoff";

interface GoldenCase {
  name: string;
  legs: Leg[];
  expected: {
    net_cost: number;
    breakevens: number[];
    max_profit: number | null;
    max_loss: number | null;
    unlimited_profit: boolean;
    unlimited_loss: boolean;
    upside_slope: number;
    downside_slope: number;
    underlying_prices: number[];
    pnl_at_expiry: number[];
  };
}

const golden = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("../../api/tests/fixtures/payoff_golden.json", import.meta.url)),
    "utf8",
  ),
) as {
  parameters: {
    spot: number;
    price_range: [number, number];
    points: number;
    option_multiplier: number;
  };
  cases: GoldenCase[];
};

describe("golden file agreement with the Python engine", () => {
  it("uses the same contract multiplier", () => {
    expect(OPTION_MULTIPLIER).toBe(golden.parameters.option_multiplier);
  });

  it("covers the structures that are easy to get wrong", () => {
    const names = golden.cases.map((c) => c.name);
    expect(names).toContain("long_put");
    expect(names).toContain("covered_call");
    expect(names).toContain("call_ratio_spread");
  });

  it.each(golden.cases.map((c) => [c.name, c] as const))(
    "reproduces %s exactly",
    (_name, testCase) => {
      const { spot, price_range: range, points } = golden.parameters;
      const curve = buildPayoffCurve(testCase.legs, spot, range, points);
      const expected = testCase.expected;

      expect(curve.netCost).toBeCloseTo(expected.net_cost, 9);
      expect(curve.maxProfit).toEqual(
        expected.max_profit === null ? null : expect.closeTo(expected.max_profit, 9),
      );
      expect(curve.maxLoss).toEqual(
        expected.max_loss === null ? null : expect.closeTo(expected.max_loss, 9),
      );
      expect(curve.upsideSlope).toBeCloseTo(expected.upside_slope, 9);
      expect(curve.downsideSlope).toBeCloseTo(expected.downside_slope, 9);

      expect(curve.breakevens).toHaveLength(expected.breakevens.length);
      curve.breakevens.forEach((value, i) => {
        expect(value).toBeCloseTo(expected.breakevens[i] as number, 9);
      });

      expect(curve.pnlAtExpiry).toHaveLength(expected.pnl_at_expiry.length);
      curve.pnlAtExpiry.forEach((value, i) => {
        expect(value).toBeCloseTo(expected.pnl_at_expiry[i] as number, 9);
      });
    },
  );

  it("agrees on what is unlimited", () => {
    for (const testCase of golden.cases) {
      const shape = analysePayoff(testCase.legs);
      expect(shape.maxProfit === null).toBe(testCase.expected.unlimited_profit);
      expect(shape.maxLoss === null).toBe(testCase.expected.unlimited_loss);
    }
  });
});

describe("bounded versus unbounded", () => {
  it("a long put's profit is large but finite, because the stock stops at zero", () => {
    const shape = analysePayoff([
      { kind: "put", quantity: 1, premium: 4, strike: 100 },
    ]);
    expect(shape.maxProfit).toBeCloseTo(100 * OPTION_MULTIPLIER - 400, 9);
    expect(shape.maxLoss).toBeCloseTo(-400, 9);
  });

  it("a naked short call loses without limit", () => {
    const shape = analysePayoff([
      { kind: "call", quantity: -1, premium: 5, strike: 100 },
    ]);
    expect(shape.maxLoss).toBeNull();
    expect(shape.maxProfit).toBeCloseTo(500, 9);
  });

  it("a covered call's loss is bounded even though P/L falls with the stock", () => {
    const shape = analysePayoff([
      { kind: "stock", quantity: 100, premium: 100 },
      { kind: "call", quantity: -1, premium: 3, strike: 105 },
    ]);
    expect(shape.maxLoss).toBeCloseTo(-9700, 9);
    expect(shape.maxProfit).toBeCloseTo(800, 9);
  });
});

describe("breakevens", () => {
  it("does not depend on the plotting grid", () => {
    const legs: Leg[] = [
      { kind: "call", quantity: 1, premium: 5, strike: 100 },
      { kind: "call", quantity: -1, premium: 1.5, strike: 110 },
    ];
    const coarse = buildPayoffCurve(legs, 100, undefined, 5);
    const fine = buildPayoffCurve(legs, 100, undefined, 1001);
    expect(coarse.breakevens).toEqual(fine.breakevens);
    expect(coarse.maxProfit).toEqual(fine.maxProfit);
  });

  it("finds one beyond the plotted range", () => {
    const curve = buildPayoffCurve(
      [{ kind: "call", quantity: 1, premium: 5, strike: 100 }],
      100,
      [60, 102],
      11,
    );
    expect(curve.breakevens).toHaveLength(1);
    expect(curve.breakevens[0]).toBeCloseTo(105, 9);
    expect(Math.max(...curve.underlyingPrices)).toBeLessThan(105);
  });

  it("finds both sides of a ratio spread", () => {
    const shape = analysePayoff([
      { kind: "call", quantity: 1, premium: 5, strike: 100 },
      { kind: "call", quantity: -2, premium: 1.5, strike: 110 },
    ]);
    expect(shape.breakevens).toHaveLength(2);
    expect(shape.breakevens[0]).toBeCloseTo(102, 9);
    expect(shape.breakevens[1]).toBeCloseTo(118, 9);
  });
});

describe("leg validation", () => {
  it("rejects a zero quantity", () => {
    expect(() => analysePayoff([{ kind: "call", quantity: 0, premium: 5, strike: 100 }]))
      .toThrow(LegError);
  });

  it("explains that a short leg uses a negative quantity", () => {
    expect(() => analysePayoff([{ kind: "call", quantity: 1, premium: -5, strike: 100 }]))
      .toThrow(/negative quantity/);
  });

  it("rejects an option with no strike", () => {
    expect(() => analysePayoff([{ kind: "put", quantity: 1, premium: 5 }]))
      .toThrow(/positive strike/);
  });

  it("rejects a stock leg carrying a strike", () => {
    expect(() =>
      analysePayoff([{ kind: "stock", quantity: 100, premium: 100, strike: 95 }]),
    ).toThrow(/no strike/);
  });

  it("rejects an empty position", () => {
    expect(() => analysePayoff([])).toThrow(/at least one leg/);
  });

  it("rejects a non-positive spot", () => {
    expect(() =>
      buildPayoffCurve([{ kind: "call", quantity: 1, premium: 5, strike: 100 }], 0),
    ).toThrow(/positive/);
  });
});

describe("cost and labelling", () => {
  it("signs the cash flow from the quantity", () => {
    expect(legCost({ kind: "call", quantity: 1, premium: 5, strike: 100 })).toBe(500);
    expect(legCost({ kind: "call", quantity: -1, premium: 5, strike: 100 })).toBe(-500);
    expect(legCost({ kind: "stock", quantity: 100, premium: 100 })).toBe(10000);
  });

  it("describes a position readably", () => {
    expect(
      describePosition([
        { kind: "call", quantity: 1, premium: 5, strike: 105 },
        { kind: "call", quantity: -2, premium: 1.5, strike: 110 },
        { kind: "stock", quantity: 100, premium: 100 },
      ]),
    ).toBe("Long 1 105C / Short 2 110C / Long 100 shares");
  });

  it("prices a straddle symmetrically around the strike", () => {
    const legs: Leg[] = [
      { kind: "call", quantity: 1, premium: 5, strike: 100 },
      { kind: "put", quantity: 1, premium: 5, strike: 100 },
    ];
    expect(payoffAtExpiry(legs, 90)).toBeCloseTo(payoffAtExpiry(legs, 110), 9);
  });
});
